
# Config file for automatic testing at travis-ci.org

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
#  - "2.7"
#  - "3.5"
  - "3.6"
  - "3.7"
# os:
#   - linux
#   - osx
before_install:
  - sudo apt-get install gfortran
install:
  - pip install --upgrade cython numpy ipython scipy astropy matplotlib pytest-cov codecov numba
  - pip install git+https://github.com/grburgess/gbm_drm_gen
  - python setup.py install
script:
  - python -m pytest -vv --cov=cosmogrb/
  - codecov --token=39cbd278-9065-488d-b323-b2b3dcc4ce1e









