
# Config file for automatic testing at travis-ci.org

language: python
python:

  - "3.6"
  - "3.7"
  - "3.8"
# os:
#   - linux
#   - osx
#env:
#  NUMBA_DISABLE_JIT=1

before_install:
  - sudo apt-get install gfortran
install:
  - pip install -e git://github.com/person142/numba-scipy.git@pin-scipy#egg=numba-scipy
  - pip install --upgrade cython numpy numba scipy pytest-cov codecov
  - pip install git+https://github.com/grburgess/gbm_drm_gen
  - python setup.py install
script:
  - python -m pytest -vv --log-cli-level=DEBUG  --cov=cosmogrb/
  - codecov --token=39cbd278-9065-488d-b323-b2b3dcc4ce1e









