# Config file for automatic testing at travis-ci.org

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
#  - "2.7"
  - "3.5"
  - "3.6"
#  - "3.7-dev"
install:
  - pip install numpy ipython scipy astropy  matplotlib pytest-cov codecov numba
  - python setup.py install
script:
  - python -m pytest -vv --cov=cosmogrb/
  - codecov --token=39cbd278-9065-488d-b323-b2b3dcc4ce1e






